### ISSUE TITLE
Black & Red Chart

### ISSUE THREAD

**Issue by snuggs** [devpunks/blackhistory.io#1]
- [x] - Find simple javascritpt chart
- [x] - When in the black background is black foreground is white.
- [x] - When **in the red color should be #ff0000

**Comment by snuggs** [comment]
@soulmutbuttas we need to find a lightweight javascript charting system. Many use heavyweight libraries like one called D3.js but it's so damn complex and not worth the sluggish ass 3G network latency (nor bandwidth cost for higher).

## References
https://d3js.org

**Comment by snuggs** [comment]
@soulmutbuttas EUREKA!

https://developers.google.com/chart/

Other open source options. They should have some examples on the site or i'd leave immediately. [(TL;DR;)](https://www.urbandictionary.com/define.php?term=tl%3Bdr)
https://github.com/zingchart/awesome-charting#free-and-open-source-libraries

**Comment by scottmacdowell** [comment]
If the client is going to be written in React, I would suggest using 

[ReCharts](http://recharts.org/#/en-US/)
https://github.com/recharts/recharts

(D3 based)

**Comment by snuggs** [comment]
@soulmutbuttas EUREKA! Found ALL historic data by the day. http://www.ic.unicamp.br/~stolfi/temp/2015-02-10-refprice-01d.txt

However we have to extrapolate what we say the "day price" is from the following values:
Open, High, Low, Close

For example
![capture d ecran 2018-02-10 a 15 23 02](https://user-images.githubusercontent.com/38223/36066398-b3d9d5c4-0e76-11e8-9a91-0627178873f2.png)

**Comment by snuggs** [comment]
@soulmutbuttas  on second thought I think Historical Price is better suited for market price and Historical Cost better suited for personal transactions.

**Comment by snuggs** [comment]
@soulmutbuttas @scottmacdowell @lafetaylor2 https://blackhistoryio-wsewcasvhk.now.sh

If I can get a [LGTM (Looks Good To Me)](https://www.urbandictionary.com/define.php?term=LGTM) in a comment after review from one of you we can merge this and move on to the candlesticks.

Thanks! 🙏  Peace! :peace_symbol:
